apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T06:16:08Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "510"
  uid: c79dcace-2694-4257-8108-5c3442a07273
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.159.199
  clusterIPs:
  - 10.100.159.199
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30581
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
