apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T06:49:41Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1897"
  uid: cecf23d5-ce3a-4d38-b922-8a70ab5351ec
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.224.30
  clusterIPs:
  - 10.98.224.30
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31159
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
